services:
  app-server:
    image: nginx:alpine
    container_name: nginx-gateway
    volumes:
      - "../nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro"
    ports:
      - "8080:80"
    networks:
      - api-networks
    depends_on:
      - auth
      - product

  auth:
    build:
      context: ../auth
      dockerfile: Dockerfile
    ports:
      - "3000"
    container_name: auth
    networks:
      - api-networks

  product:
    build:
      context: ../product
      dockerfile: Dockerfile
    ports:
      - "4000"
    container_name: product
    networks:
      - api-networks

networks:
  api-networks: 
