services:
  auth:
    build:
      context: ../auth
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: auth
    networks:
      - api-networks

  product:
    build:
      context: ../product
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    container_name: product
    networks:
      - api-networks

networks:
  api-networks: 
    external: true

