_format_version: "3.0"

services:
  - name: auth
    url: http://auth:3000
    routes:
      - name: auth-route
        paths:
          - /auth
        strip_path: true

  - name: product
    url: http://product:4000
    routes:
      - name: product-route
        paths:
          - /product
        strip_path: true
    plugins:
      - name: jwt
        config:
          uri_param_names: ["jwt"]
          claims_to_verify: ["exp"]
          key_claim_name: "iss"
          secret_is_base64: false
          run_on_preflight: true
          header_names: ["Authorization"]

consumers:
  - username: api-client
    jwt_secrets:
      - key: my-jwt-key
        secret: test # jwt secrets

